# Generated by Django 4.1.6 on 2023-07-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tel',
            new_name='telmtn',
        ),
        migrations.AddField(
            model_name='profile',
            name='adresse',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telorange',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
