# Generated by Django 4.2.14 on 2024-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataafriquehub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='review',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
